sudo: required
language: php
php:
#  - '5.3'
#  - '5.4'
#  - '5.5'
  - '5.6'
#  - '7.0'
  - '7.1'

before_install:
  - sudo apt-get -y install git zip php5-cli php5-curl

before_script:
  - composer install

script:
    - vendor/bin/phpunit --coverage-clover=coverage.xml

after_script:
    - bash <(curl -s https://codecov.io/bash)